# Generated by Django 4.2.20 on 2025-03-27 01:24

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user_avatar_path, verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, help_text='A brief description about yourself', verbose_name='Bio')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('newsletter_subscription', models.BooleanField(default=False, verbose_name='Subscribe to Newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
